//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int Commande_id { get; set; }
        public string Commande_etat { get; set; }
        public bool Commande_paiement { get; set; }
        public string Commande_modepaiement { get; set; }
        public Nullable<System.DateTime> Commande_date { get; set; }
        public double Commande_totalHT { get; set; }
        public double Commande_totalTTC { get; set; }
        public int Client_id { get; set; }
        public int Adresse_id { get; set; }
        public int Tva_id { get; set; }
        public Nullable<System.DateTime> Commande_datepaiement { get; set; }
        public string NomClient { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == DBNull.Value) return false;
            Commande c = (Commande)obj;
            return Commande_id == c.Commande_id;
        }

    }
}
