//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contient
    {
        public int Produit_qtcommande { get; set; }
        public double Produit_prixHT { get; set; }
        public int Produit_reference { get; set; }
        public string Commande_reference { get; set; }
    
        public virtual Produits Produits { get; set; }
    }
}
