//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon_de_livraison
    {
        public int Bonlivraison_numero { get; set; }
        public Nullable<System.DateTime> Bonlivraison_date { get; set; }
        public int Commande_reference { get; set; }
        public int Adresse_reference { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
