 //------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Commande = new HashSet<Commande>();
        }
    
        public int Client_id { get; set; }
        public string Client_nom { get; set; }
        public string Client_prenom { get; set; }
        public bool Client_categorie { get; set; }
        public int Client_coefficient { get; set; }
        public int Commercial_numero { get; set; }
        public int Adresse_id { get; set; }
        public bool Client_statut { get; set; }
        
        
        public string Client_siret { get; set; }   
      
        public virtual ICollection<Commande> Commande { get; set; }
    }
}
