//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.Fournit = new HashSet<Fournit>();
        }
    
        public int Fournisseur_code { get; set; }
        public bool Fournisseur_type { get; set; }
        public string Fournisseur_nom { get; set; }
        public string Fournisseur_pays { get; set; }
        public string Fournisseur_adresse { get; set; }
        public string Fournisseur_codepostal { get; set; }
        public string Fournisseur_ville { get; set; }
        public string Fournisseur_mail { get; set; }
        public string Fournisseur_telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fournit> Fournit { get; set; }
    }
}
